coaches/urls.py
from django.conf.urls import patterns, include, url
from coaches import views


urlpatterns = patterns('',
    url(r'^$', views.CoachListView.as_view(), name='list'),
    url(r'^add/$', views.CoachCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CoachUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CoachDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/$', views.CoachDetailView.as_view(), name='item'),
)

pybursa/urls.py
from django.views.generic import TemplateView


from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import ComplaintView


urlpatterns = patterns('',
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^complaint/$', ComplaintView.as_view(), name="complaint"),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

students/urls.py
from django.conf.urls import patterns, include, url
from students import views


urlpatterns = patterns('',
    url(r'^$', views.students_list, name='list'),
    url(r'^add/$', views.students_edit, name='add'),
    url(r'^edit/(?P<student_id>\d+)/$', views.students_edit, name='edit'),
    url(r'^remove/(?P<student_id>\d+)/$', views.students_remove, name='remove'),
    url(r'^(?P<student_id>\d+)/$', views.students_item, name='item'),
)

students/models.py
from django.db import models


class Student(models.Model):

    def __unicode__(self):
        return self.surname

    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    package = models.CharField(max_length=15,
                               choices=(('Standart','Standart'),
                                        ('Gold','Gold')),
                               default='Standart')
    course = models.ForeignKey('courses.Course', default=1)
    dossier = models.OneToOneField('extradata.Dossier', blank=True, null=True)

students/views.py
from django.shortcuts import render, redirect
from django import forms
from students.models import Student
from courses.models import Course
from extradata.models import Dossier
from django.utils.translation import ugettext_lazy as _

import logging
logger = logging.getLogger(__name__)


class StudentForm(forms.Form):
    CHOICES = (('Standart', 'Standart'),
               ('Gold', 'Gold'))
    student_name = forms.CharField(label=_("Name"), max_length=100)
    student_surname = forms.CharField(label=_("Surname"), max_length=255)
    student_date_of_birth = forms.DateField(label=_("Date of bith"))
    student_email = forms.EmailField()
    student_phone = forms.CharField(label=_("Phone number"), max_length=15)
    student_package = forms.ChoiceField(label=_("Package"), widget=forms.RadioSelect,
                                        choices=CHOICES)
    student_course = forms.ModelChoiceField(label=_("Course"), queryset=Course.objects.all(),)
    student_dossier = forms.ModelChoiceField(label=_("Dossier"), queryset=Dossier.objects.all(),required=False)



def students_list(request):
    students = Student.objects.all()
    return render(request, 'students/list.html', {'students': students})

def students_item(request, student_id):
    student = Student.objects.get(id=int(student_id))
    return render(request, 'students/item.html', {'student': student})

def students_edit(request, student_id=None):
    if student_id is None:
        student = Student()
    else:
        student = Student.objects.get(id=student_id)
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            student.name = form.cleaned_data['student_name']
            student.surname = form.cleaned_data['student_surname']
            student.package = form.cleaned_data['student_package']
            student.date_of_birth = form.cleaned_data['student_date_of_birth']
            student.email = form.cleaned_data['student_email']
            student.phone = form.cleaned_data['student_phone']
            student.course = form.cleaned_data['student_course']
            student.dossier = form.cleaned_data['student_dossier']
            try:
                student.save()
                logger.info("Student %s %s was updated." % (student.name, student.surname))
            except:
                logger.error("Student %s %s didn't update." % (student.name, student.surname))
            return redirect('students:list')

    else:
        form = StudentForm(initial={'student_name': student.name,
                                    'student_surname': student.surname,
                                    'student_date_of_birth': student.date_of_birth,
                                    'student_email': student.email,
                                    'student_phone': student.phone,
                                    'student_package': student.package,
                                    'student_course': student.course,
                                    'student_dossier': student.dossier})
    return render(request, 'students/edit.html', {'form': form})

def students_remove(request, student_id):
    student = Student.objects.get(id=student_id)
    try:
        student.delete()
        logger.info("Student %s %s was removed." % (student.name, student.surname))
    except:
        logger.error("Student %s %s didn't romove." % (student.name, student.surname))
    return redirect('students:list')

templates/students/base.html
{% extends "base.html" %}

{% block title %}Students{% endblock %}

{% block 'header' %}
  {% include "header.html" with active_students="active" %}
{% endblock %}

{% block 'contents' %}{% endblock %}

templates/students/edit.html
{% extends "students/base.html" %}
{% load i18n %}

  {% block 'contents' %}
    <div class="container">
      <h1>{% trans "Student edit item" %}:</h1>
      <p>* - {% trans "required fields" %}</p>
          <form method='POST'>
            {% csrf_token %}
            {#{{ form.as_p }}#}
            <ul class="list-group">
              {% for field in form %}
                  <li class="list-group-item">
                    {% if field.errors %}
                      <div class="alert alert-danger" role="alert">
                        {{ field.errors }}
                      </div>
                    {% endif %}
                    {% if field.field.required %}
                      <span class="special_class">*
                      {{ field.label_tag }} {{ field }}</span>
                    {% else %}
                      {{ field.label_tag }} {{ field }}
                    {% endif %}
                  </li>
              {% endfor %}
              <li class="list-group-item"><input  type="submit" value="{% trans "Send" %}">
              </li>
            </ul>
          </form>
    </div><!-- /.container -->
  {% endblock %}

templates/students/item.html
{% extends "students/base.html" %}
{% load i18n %}

  {% block 'contents' %}
    <div class="container">
      <h1>{% trans "Student" %}: {{student.surname}}  {{student.name}}</h1>
      {% include "controlpl.html" with add_url='students:add' edit_url='students:edit' del_url='students:remove' item_id=student.id %}
      <ul class="list-group">
        <li class="list-group-item">id: {{student.id}}</li>
        <li class="list-group-item">{% trans "course" %}: {{student.course}}</li>
        <li class="list-group-item">Email: {{student.email}}</li>
        <li class="list-group-item">{% trans "Phone number" %}: {{student.phone}}</li>
        <li class="list-group-item">{% trans "Package" %}: {{student.package}}</li>
        {% if student.dossier != None %}
          <li class="list-group-item">{% trans "Dossier" %}: {{student.dossier}}</li>
        {% endif %}
      </ul>
    </div><!-- /.container -->
  {% endblock %}

templates/students/list.html
{% extends "students/base.html" %}
{% load i18n %}

{% block 'contents' %}
  <div class="container">
      <h1>{% trans "IT Bursa students list:" %}</h1>
      <ul class="list-group">
        {% for student in students %}
          <li class="list-group-item">
            <a href="{% url 'students:item' student.id %}">
              {{student.name}}  {{student.surname}}
            </a>
            <div align="right">
              <a href="{% url 'students:edit' student.id %}" >
                <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                </span>
              </a>
              <a href="{% url 'students:remove' student.id %}" >
                <span class="glyphicon glyphicon-remove" aria-hidden="true">
                </span>
              </a>
            </div>
          </li>
        {% endfor %}
        <li class="list-group-item">
          <form>
          <button type="submit" class="btn btn-default"
            formaction="{% url 'students:add' %}"><span
            class="glyphicon glyphicon-plus" aria-hidden="true">
            </span>{% trans " Add item" %}</button>

          </form>
        </li>
      </ul>
  </div><!-- /.container -->
{% endblock %}