coaches/urls.py
from django.conf.urls import patterns, include, url
from coaches import views


urlpatterns = patterns('',
    url(r'^$', views.CoachListView.as_view(), name='list'),
    url(r'^add/$', views.CoachCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CoachUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CoachDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/$', views.CoachDetailView.as_view(), name='item'),
)

pybursa/urls.py
from django.views.generic import TemplateView


from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import ComplaintView


urlpatterns = patterns('',
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^complaint/$', ComplaintView.as_view(), name="complaint"),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0050)http://getbootstrap.com/examples/starter-template/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>ItBursa / {% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <!--<link href="{% static "dist/css/bootstrap.min.css" %}" rel="stylesheet">-->
    <link href="{% static "dist/css/bootstrap.css" %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static "examples/starter-template.css" %}" rel="stylesheet">

  </head>

  <body>

    {% block 'header' %}

    {% endblock %}

    {% block 'contents' %}

    {% endblock %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="jquery.min.js"></script>
    <script src="bootstrap.min.js"></script>


</body></html>

templates/complaint.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block title %}Complaint{% endblock %}

{% block 'header' %}
  {% include "header.html" with active_complaint="active" %}
{% endblock %}

{% block 'contents' %}
    <div class="container">
        {% if messages %}
          <ul class="list-group">
          {% for message in messages %}
            <li class="list-group-item">
              <div
                {% if message.tags = 'success' %}
                  class="alert alert-success"
                {% else %}
                  class="alert alert-danger"
                {% endif %} role="alert">
                        {{ message }}
              </div>
            </li>
          {% endfor %}
          </ul>
        {% endif %}
        <h1>{% trans "Complaint form:" %}</h1>
        <p>* - {% trans "required fields" %}</p>
        <form method="post">
          {% csrf_token %}
          <ul class="list-group">
            {% for field in form %}
                  <li class="list-group-item">
                    {% if field.errors %}
                      <div class="alert alert-danger" role="alert">
                        {{ field.errors }}
                      </div>
                    {% endif %}
                    {% if field.field.required %}
                      <span class="special_class">*
                      {{ field.label_tag }} {{ field }}</span>
                    {% else %}
                      {{ field.label_tag }} {{ field }}
                    {% endif %}
                  </li>
            {% endfor %}
            <li class="list-group-item"><input  type="submit" value="{% trans "Send" %}"></li>
          </ul>
        </form>
    </div><!-- /.container -->
{% endblock %}

templates/complaint_body.html
Достопочтенный и многоуважаемый преподаватель {{ coach_name}} {{ coach_surname}}!
Спешу уведомить Вас о неподобающем поведении студента {{ student_surname}} (курса "{{ course }}").
Дело в следующем. {{ body_complaint }}
С уважением, Аноним.

templates/controlpl.html
{% load i18n %}

<div class="btn-group" role="group" aria-label="...">
  <form>
    <button type="submit" class="btn btn-default"
        formaction="{% url add_url %}">
        <span class="glyphicon glyphicon-plus" aria-hidden="true">
            </span>{% trans " Add item" %}</button>
    <button type="submit" class="btn btn-default"
        formaction="{% url edit_url item_id %}">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                </span>{% trans " Edit item" %}</button>
    <button type="submit" class="btn btn-default"
        formaction="{% url del_url item_id %}">
        <span class="glyphicon glyphicon-remove" aria-hidden="true">
                </span>{% trans " Remove" %}</button>
  </form>
</div>

templates/header.html
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}


<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">IT Bursa</a>
        </div>
        {% block 'menu' %}
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class={{ active_home }}><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
              <li class={{ active_students }}><a href="{% url 'students:list' %}">{% trans "Students" %}</a></li>
              <li class={{ active_courses }}><a href="{% url 'courses:list' %}">{% trans "Courses" %}</a></li>
              <li class={{ active_coaches }}><a href="{% url 'coaches:list' %}">{% trans "Coaches" %}</a></li>
              <li class={{ active_complaint }}><a href="{% url 'complaint' %}">{% trans "Complaint" %}</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'admin:index' %}">{% trans "Admin site" %}</a></li>
              {% if LANGUAGES %}
              <li>
                <div class="btn-group" data-toggle="buttons">

                    {% for LANGUAGE in LANGUAGES %}
                      <label
                        {% if LANGUAGE_CODE == LANGUAGE.0 %}
                            class="btn btn-primary active"
                        {% else %}
                            class="btn btn-primary"
                        {% endif %}>
                        <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="language" type="hidden" value={{ LANGUAGE.0 }} >
                        <input type="submit" class="btn btn-default" name="options" id={{ LANGUAGE.0 }}
                            autocomplete="off" checked value={{ LANGUAGE.0 }}>
                        </form>
                      </label>
                    {% endfor %}
                </div>
              </li>
              {% endif %}

            </ul>
          </div><!--/.nav-collapse -->
        {% endblock %}
      </div>
</nav>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block 'header' %}
  {% include "header.html" with active_home="active" %}
{% endblock %}

{% block 'contents' %}
    <div class="container">

      <div class="starter-template">
        <h1>IT Bursa homepage</h1>
        <p class="lead"> Professional programming courses.
        <br> Python, JavaScript, Ruby and more.</p>
        <h1>COME WITH US!</h1>
        <div class="panel panel-default">
          <img src="{% static "img/ComeWithUs.jpg" %}" width="600" height="600">
          </div>
        <audio controls loop>
            <source src="{% static "audio/cwus.mp3" %}" type="audio/mpeg">
        </audio>
      </div>

    </div><!-- /.container -->
{% endblock %}

templates/product.html
{% load static %}<!DOCTYPE html>
<!-- saved from url=(0050)http://getbootstrap.com/examples/starter-template/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Automating the process of learning</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "dist/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "examples/starter-template.css" %}" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li ><a href="/">Home</a></li>
            <li><a href="/products">Products</a></li>
            <li class="active"><a href="/product">Product</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="starter-template">
        <div class="table-responsive">
            <table class="table table-striped">
              <tbody>
                <tr>
                  <td></td>
                  <td><img src="{% static "img/PyBursaLogo.png" %}" width="100" height="120"><h1>Python курсы</h1>
                      <p class="lead">

                          Надоело собирать знания по крупицам?

                          Наибольшей проблемой всех учебников и статей, по которым начинают изучать Python - это отсутствие практики с освоенным материалом. Можно читать тонны ресурсов по веб-программированию на Python - и не научиться ничему, потому что знания, которые Вы не успели применить, очень быстро забываются. Многие начинающие сдаются на полпути, так как устают, им надоедает бесконечное блуждание по сети в поисках крупиц информации, из которых трудно собрать общую картину.</p></td>
                </tr>
              </tbody>
            </table>
          </div>

      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "/js/jquery.min.js" %}"></script>
    <script src="{% static "/dist/js/bootstrap.min.js" %}"></script>


</body></html>

templates/products.html
{% load static %}<!DOCTYPE html>
<!-- saved from url=(0050)http://getbootstrap.com/examples/starter-template/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Automating the process of learning</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "dist/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "examples/starter-template.css" %}" rel="stylesheet">

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li class="active"><a href="/products">Products</a></li>
            <li><a href="/product">Product</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Logo</th>
                  <th>Name</th>
                  <th>Date</th>
                  <th>Website</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><img src="{% static "img/PyBursaLogo.png" %}" width="50" height="60"></td>
                  <td>Python/Django</td>
                  <td>16 февраля - 17 апреля</td>
                  <td><a href = "http://pybursa.com/">pybursa.com</a></td>
                </tr>
                <tr>
                  <td><img src="{% static "img/RubyBursaLogo.png" %}" width="50" height="60"></td>
                  <td>Ruby</td>
                  <td>17 ноября-18 января</td>
                  <td><a href = "http://rubybursa.com/">rubybursa.com</a></td>
                </tr>
                <tr>
                  <td><img src="{% static "img/JSBursaLogo.png" %}" width="50" height="60"></td>
                  <td>JS</td>
                  <td>2 февраля - 3 апреля</td>
                  <td><a href = "http://jsbursa.com/">jsbursa.com</a></td>
                </tr>
              </tbody>
            </table>
          </div>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "/js/jquery.min.js" %}"></script>
    <script src="{% static "/dist/js/bootstrap.min.js" %}"></script>


</body></html>