coaches/urls.py
from django.conf.urls import patterns, include, url
from coaches import views


urlpatterns = patterns('',
    url(r'^$', views.CoachListView.as_view(), name='list'),
    url(r'^add/$', views.CoachCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CoachUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CoachDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/$', views.CoachDetailView.as_view(), name='item'),
)

courses/urls.py
from django.conf.urls import patterns, include, url
from courses import views


urlpatterns = patterns('',
    url(r'^$', views.CourseListView.as_view(), name='list'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='item'),
)

pybursa/urls.py
from django.views.generic import TemplateView


from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import ComplaintView


urlpatterns = patterns('',
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^complaint/$', ComplaintView.as_view(), name="complaint"),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

courses/models.py
from django.db import models
from django.contrib import admin


class Course(models.Model):

    def __unicode__(self):
        return self.technology

    technology = models.CharField(max_length=15,
                                  choices=(('Python','Python/Django'),
                                           ('JS','JavaScript'),
                                           ('Ruby','Ruby on rails')),
                                  default='Python')
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=True, null=True)
    description = models.CharField(max_length=255)
    teacher = models.ForeignKey('coaches.Coach', default=1,
                                 related_name='teacher')
    assistant = models.ForeignKey('coaches.Coach', blank=True, null=True,
                                   related_name='assistant')
    start_date = models.DateField()
    finish_date = models.DateField()
    venue = models.ForeignKey('extradata.Address', blank=True, null=True)

courses/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView,UpdateView, DeleteView)
from django import forms
from courses.models import Course

import logging
logger = logging.getLogger(__name__)


class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course


class CourseListView(ListView):
    model = Course
    template_name = 'courses/list.html'
    context_object_name = 'courses'


class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/item.html'
    context_object_name = 'course'


class CourseUpdateView(UpdateView):
    model = Course
    template_name = 'courses/edit.html'
    success_url = reverse_lazy('courses:list')
    context_object_name = 'course'

    def form_valid(self, form):
        try:
            form.save()
            logger.info("Course %s %s was updated." % (form.cleaned_data['name'], form.cleaned_data['description']))
        except:
            logger.error("Course %s %s didn't update." % (form.cleaned_data['name'], form.cleaned_data['description']))
        return super(CourseUpdateView, self).form_valid(form)


class CourseCreateView(CreateView):
    model = Course
    template_name = 'courses/edit.html'
    form_class = CourseModelForm
    success_url = reverse_lazy('courses:list')
    context_object_name = 'course'

    def form_valid(self, form):
        try:
            form.save()
            logger.info("Course %s %s was created." % (form.cleaned_data['name'], form.cleaned_data['description']))
        except:
            logger.error("Course %s %s didn't create." % (form.cleaned_data['name'], form.cleaned_data['description']))
        return super(CourseCreateView, self).form_valid(form)


class CourseDeleteView(DeleteView):
    template_name = 'courses/remove.html'
    model = Course
    success_url = reverse_lazy('courses:list')

    def delete(self, request, *args, **kwargs):
        course_obj =  self.get_object()
        try:
            course_obj.delete()
            logger.info("Course %s %s was removed." % (course_obj.name, course_obj.description))
        except:
            logger.error("Course %s %s didn't remove." % (course_obj.name, course_obj.description))
        return redirect(self.success_url)

templates/courses/base.html
{% extends "base.html" %}

{% block title %}Courses{% endblock %}

{% block 'header' %}
  {% include "header.html" with active_courses="active" %}
{% endblock %}

{% block 'contents' %}{% endblock %}

templates/courses/edit.html
{% extends "courses/base.html" %}


  {% block 'contents' %}
    <div class="container">
      <h1>Course edit item:</h1>
      <p>* - required fields</p>
          <form method='POST'>
            {% csrf_token %}
            {#{{ form.as_p }}#}
            <ul class="list-group">
              {% for field in form %}
                  <li class="list-group-item">
                    {% if field.errors %}
                      <div class="alert alert-danger" role="alert">
                        {{ field.errors }}
                      </div>
                    {% endif %}
                    {% if field.field.required %}
                      <span class="special_class">*
                      {{ field.label_tag }} {{ field }}</span>
                    {% else %}
                      {{ field.label_tag }} {{ field }}
                    {% endif %}
                  </li>
              {% endfor %}
              <li class="list-group-item"><input  type="submit" value="Send">
              </li>
            </ul>
          </form>
    </div><!-- /.container -->
  {% endblock %}

templates/courses/item.html
{% extends "courses/base.html" %}

  {% block 'contents' %}
    <div class="container">
      <h1>Course name: {{course.name}}</h1>
      {% include "controlpl.html" with add_url='courses:add' edit_url='courses:edit' del_url='courses:remove' item_id=course.id %}
      <ul class="list-group">
        <li class="list-group-item">Description: {{course.description}}</li>
        <li class="list-group-item">Start date: {{course.start_date}}</li>
        <li class="list-group-item">Finish date: {{course.finish_date}}</li>
        <li class="list-group-item">Teacher: {{course.teacher}}
            {{course.teacher.name}}</li>
        {% if course.assistant != None %}
            <li class="list-group-item">Assistent: {{course.assistant}}
                {{course.assistant.name}}</li>
        {% endif %}
        {% if course.venue != None %}
          <li class="list-group-item">Venue: {{course.venue}}
        {% endif %}
      </ul>
    </div><!-- /.container -->
  {% endblock %}

templates/courses/list.html
{% extends "courses/base.html" %}
{% load i18n %}

  {% block 'contents' %}
    <div class="container">
      <h1>{% trans "IT Bursa courses list:" %}</h1>
      <table class="table">
      <tr>
        <th>{% trans "Course name" %}</th>
        <th>{% trans "Start date" %}</th>
        <th>{% trans "Finish date" %}</th>
        <th></th>
      </tr>
        {% for course in courses %}
          <tr>
            <td><a href="{% url 'courses:item' course.id %}">
              {{course.name}}</a></td>
            <td>{{course.start_date}}</td>
            <td>{{course.finish_date}}</td>
            <td>
              <div align="right">
                <a href="{% url 'courses:edit' course.id %}" >
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                  </span>
                </a>
                <a href="{% url 'courses:remove' course.id %}" >
                  <span class="glyphicon glyphicon-remove" aria-hidden="true">
                  </span>
                </a>
              </div>
            </td>
          </tr>

        {% endfor %}
        <tr><td><form>
          <button type="submit" class="btn btn-default"
            formaction="{% url 'courses:add' %}"><span
            class="glyphicon glyphicon-plus" aria-hidden="true">
            </span>{% trans " Add item" %}</button>
          </form></td></tr>
      </table>
    </div><!-- /.container -->
  {% endblock %}

templates/courses/remove.html
{% extends "courses/base.html" %}

  {% block 'contents' %}
    <div class="container">
    <h1>Remov item: </h1>
    <form action="" method="post">
      {% csrf_token %}
      <div>Do you want to remove {{ course }}?</div>
      <input type="submit" value="Yes" />
    </form>
    </div><!-- /.container -->
  {% endblock %}