coaches/urls.py
from django.conf.urls import patterns, include, url
from coaches import views


urlpatterns = patterns('',
    url(r'^$', views.CoachListView.as_view(), name='list'),
    url(r'^add/$', views.CoachCreateView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', views.CoachUpdateView.as_view(), name='edit'),
    url(r'^remove/(?P<pk>\d+)/$', views.CoachDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/$', views.CoachDetailView.as_view(), name='item'),
)

pybursa/urls.py
from django.views.generic import TemplateView


from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa.views import ComplaintView


urlpatterns = patterns('',
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^coaches/', include('coaches.urls', namespace="coaches")),
    url(r'^complaint/$', ComplaintView.as_view(), name="complaint"),
    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

coaches/models.py
from django.db import models
from django.contrib.auth.models import User


class Coach(models.Model):

    def __unicode__(self):
        return self.surname

    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    position = models.CharField(max_length=15,
                                  choices=(('teacher','teacher'),
                                           ('assistant','assistant')),
                                  default='teacher')
    user = models.ForeignKey(User, default=1)
    dossier = models.OneToOneField('extradata.Dossier', blank=True, null=True)

coaches/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView,UpdateView, DeleteView)
from django import forms
from coaches.models import Coach
from courses.models import Course

import logging
logger = logging.getLogger(__name__)


class CoachModelForm(forms.ModelForm):
    class Meta:
        model = Coach


class CoachListView(ListView):
    model = Coach
    template_name = 'coaches/list.html'
    context_object_name = 'coaches'


class CoachDetailView(DetailView):
    model = Coach
    template_name = 'coaches/item.html'
    context_object_name = 'coach'

    def get_context_data(self, **kwargs):
        context = super(CoachDetailView, self).get_context_data(**kwargs)
        try:
            course = Course.objects.get(teacher=int(kwargs['object'].id))
        except:
            course = None
        context['course'] = course
        return context


class CoachUpdateView(UpdateView):
    model = Coach
    template_name = 'coaches/edit.html'
    success_url = reverse_lazy('coaches:list')
    context_object_name = 'coach'

    def form_valid(self, form):
        try:
            form.save()
            logger.info("Coach %s %s was updated." % (form.cleaned_data['name'], form.cleaned_data['surname']))
        except:
            logger.error("Coach %s %s didn't update." % (form.cleaned_data['name'], form.cleaned_data['surname']))
        return super(CoachUpdateView, self).form_valid(form)


class CoachCreateView(CreateView):
    model = Coach
    template_name = 'coaches/edit.html'
    form_class = CoachModelForm
    success_url = reverse_lazy('coaches:list')
    context_object_name = 'coach'

    def form_valid(self, form):
        try:
            form.save()
            logger.info("Coach %s %s was add." % (form.cleaned_data['name'], form.cleaned_data['surname']))
        except:
            logger.error("Coach %s %s didn't add." % (form.cleaned_data['name'], form.cleaned_data['surname']))
        return super(CoachCreateView, self).form_valid(form)


class CoachDeleteView(DeleteView):
    template_name = 'coaches/remove.html'
    model = Coach
    success_url = reverse_lazy('coaches:list')

    def delete(self, request, *args, **kwargs):
        coach_obj =  self.get_object()
        try:
            coach_obj.delete()
            logger.info("Coach %s %s was removed." % (coach_obj.name, coach_obj.surname))
        except:
            logger.error("Coach %s %s didn't remove." % (coach_obj.name, coach_obj.surname))
        return redirect(self.success_url)

templates/coaches/base.html
{% extends "base.html" %}

{% block title %}Coaches{% endblock %}

{% block 'header' %}
  {% include "header.html" with active_coaches="active" %}
{% endblock %}

{% block 'contents' %}{% endblock %}

templates/coaches/edit.html
{% extends "coaches/base.html" %}


  {% block 'contents' %}
    <div class="container">
      <h1>Coach edit item:</h1>
      <p>* - required fields</p>
          <form method='POST'>
            {% csrf_token %}
            {#{{ form.as_p }}#}
            <ul class="list-group">
              {% for field in form %}
                  <li class="list-group-item">
                    {% if field.errors %}
                      <div class="alert alert-danger" role="alert">
                        {{ field.errors }}
                      </div>
                    {% endif %}
                    {% if field.field.required %}
                      <span class="special_class">*
                      {{ field.label_tag }} {{ field }}</span>
                    {% else %}
                      {{ field.label_tag }} {{ field }}
                    {% endif %}
                  </li>
              {% endfor %}
              <li class="list-group-item"><input  type="submit" value="Send">
              </li>
            </ul>
          </form>
    </div><!-- /.container -->
  {% endblock %}

templates/coaches/item.html
{% extends "coaches/base.html" %}

  {% block 'contents' %}
    <div class="container">
      <h1>Coach name: {{coach.name}} {{coach.surname}}</h1>
      {% include "controlpl.html" with add_url='coaches:add' edit_url='coaches:edit' del_url='coaches:remove' item_id=coach.id %}
      <ul class="list-group">
        <li class="list-group-item">Position: {{coach.position}}</li>
        <li class="list-group-item">Email: {{coach.email}}</li>
        <li class="list-group-item">Phone number: {{coach.phone}}</li>
        {% if course != None %}
          <li class="list-group-item">Course: {{course.name}}</li>
        {% endif %}
        {% if coach.dossier != None %}
          <li class="list-group-item">Dossier: {{coach.dossier}}</li>
        {% endif %}
      </ul>
    </div><!-- /.container -->
  {% endblock %}

templates/coaches/list.html
{% extends "coaches/base.html" %}
{% load i18n %}

  {% block 'contents' %}
    <div class="container">
      <h1>{% trans "IT Bursa coaches:" %}</h1>
      <ul class="list-group">
        {% for coach in coaches %}
          <li class="list-group-item"><a href="{% url 'coaches:item' coach.id %}">
            {{coach.name}} {{coach.surname}} ({{coach.position}})</a>
            <div align="right">
              <a href="{% url 'coaches:edit' coach.id %}" >
                <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                </span>
              </a>
              <a href="{% url 'coaches:remove' coach.id %}" >
                <span class="glyphicon glyphicon-remove" aria-hidden="true">
                </span>
              </a>
            </div>
          </li>
        {% endfor %}
        <li class="list-group-item">
          <form>
          <button type="submit" class="btn btn-default"
            formaction="{% url 'coaches:add' %}"><span
            class="glyphicon glyphicon-plus" aria-hidden="true">
            </span>{% trans " Add item" %}</button>

          </form>
        </li>
      </ul>
    </div><!-- /.container -->
  {% endblock %}

templates/coaches/remove.html
{% extends "coaches/base.html" %}

  {% block 'contents' %}
    <div class="container">
    <h1>Remov item: </h1>
    <form action="" method="post">
      {% csrf_token %}
      <div>Do you want to remove {{ coach }}?</div>
      <input type="submit" value="Yes" />
    </form>
    </div><!-- /.container -->
  {% endblock %}